interest_list = [
    'Acting',
    'Animals',
    'Anime & Manga',
    'Architecture',
    'Art',
    'Astronomy',
    'Baking',
    'Ballet',
    'Beekeeping',
    'Birdwatching',
    'Board Games',
    'Business',
    'Calligraphy',
    'Camping',
    'Canoeing',
    'Carpentry',
    'Cars & Driving',
    'Chess',
    'Cleaning',
    'Climbing',
    'Collecting',
    'Comedy',
    'Competitive Programming',
    'Computers',
    'Concerts',
    'Cooking',
    'Cosplay',
    'Crafts',
    'Creative Pursuits',
    'Creative Reuse',
    'Cuisine',
    'Culture',
    'Cycling',
    'DIY',
    'Dance',
    'Darts',
    'Debate',
    'Design',
    'Diving & Snorkelling',
    'Drawing',
    'Education',
    'Engineering',
    'Entrepreneurship',
    'Environmental Action',
    'Exercise',
    'Family',
    'Fandom',
    'Fashion',
    'Festivals',
    'Film',
    'Fitness',
    'Frisbee',
    'Game Theory',
    'Gardening',
    'Golf',
    'Health',
    'Hiking',
    'History',
    'Horseback Riding',
    'Inline Skating',
    'Interior Design',
    'Investing',
    'Knitting',
    'Languages',
    'Law',
    'Leadership',
    'Learning',
    'Low Technology',
    'Machines',
    'Maker Culture',
    'Martial Arts',
    'Mathematics',
    'Media Production',
    'Medicine',
    'Meditation',
    'Model Building',
    'Museums',
    'Music Appreciation',
    'Music Production',
    'Nature',
    'Nightlife',
    'Origami',
    'Philosophy',
    'Photography',
    'Politics',
    'Pool',
    'Pop Culture',
    'Programming',
    'Psychology',
    'Public Speaking',
    'Puzzles',
    'Reading',
    'Religion & Spirituality',
    'Research',
    'Robotics',
    'Running',
    'Sailing',
    'Science',
    'Self-Improvement',
    'Sewing',
    'Shopping',
    'Simple Living',
    'Singing',
    'Skateboarding',
    'Skating',
    'Skiing & Snowboarding',
    'Social Media',
    'Socializing',
    'Sociology',
    'Space',
    'Sports',
    'Storytelling',
    'Strategy',
    'Surfing & Bodyboarding',
    'Swimming',
    'Tea-Making',
    'Technology',
    'Television',
    'Theatre',
    'Theme Parks',
    'Traditional Culture',
    'Travel',
    'Trivia',
    'Video Games',
    'Volunteering',
    'Walking',
    'Wellness',
    'Woodworking',
    'Writing',
    'Yoga',
]


__all__ = ['interest_list']
