upstream frontend {
    server frontend:8080;
}
upstream backend {
    server backend:8080;
}
server {
    location ~ ^/(login|login_start|myprofile|(profile|profile_interests)/[0-9a-f\-]+|notifications|interest_str/[a-z][a-z]|confirm|admin/pairing|docs|openapi\.json)$ {
        proxy_set_header Host $host;
        proxy_pass http://backend;
    }
    location / {
        proxy_set_header Host $host;
        proxy_pass http://frontend;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
