name: Simple static checks

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./randomcoffee
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - name: Install poetry
        run: pip install poetry
      - name: Install poetry project
        run: poetry install
      - name: Run checks
        run: |
          eval $(poetry env activate) &&\
          flake8 &&\
          bandit -r src
